openapi: 3.0.3
info:
  title: Aktes koppel api API
  description: Dit is het koppelstuk tussen mijn amsterdam en aktes
  version: 1.0.0
servers:
  - url: 'https://mijn.amsterdam.nl'
paths:

components:
  schemas:
